import type { Metadata } from 'next'

import { ReactNode } from 'react'
import { Geist } from 'next/font/google'

import '@/styles/globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: '/icon-blue.svg'
}

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} prose antialiased w-full h-screen grid grid-cols-4`}>
        <aside className={'col-span-1 bg-secondary border-r border-secondary'}></aside>
        <main className={'col-span-3 bg-primary'}>
          {children}
        </main>
      </body>
    </html>
  )
}
